reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true

struct_field_align_threshold = 20
max_width = 160

